args <- commandArgs(trailingOnly = TRUE)                                                                                                                                                                                                     
ipath <- args[1]                                                                                                                                                                                                                             
opath <- args[2]                                                                                                                                                                                                                             
args <- args[c(-1,-2)]                                                                                                                                                                                                                       
                                                                                                                                                                                                                                             
for (filename in args)                                                                                                                                                                                                                       
{                                                                                                                                                                                                                                            
  dataA1 <- read.table(paste(ipath,filename,sep="/"),as.is=T,header=F)                                                                                                                                                                       
                                                                                                                                                                                                                                             
  tdataA1 <- as.ts(dataA1$V3)                                                                                                                                                                                                                
  tdataA1 <- filter(c(window(tdataA1,1,300),tdataA1),filter=1/seq(5,100,4),method="recursive")[-(1:300)]                                                                                                                                     
  tdataA1 <- tdataA1-mean(tdataA1,trim=0.1)                                                                                                                                                                                                  
                                                                                                                                                                                                                                             
  resA1 <- spec.pgram(tdataA1,pad=0.3,tap=0.3,span=2,plot=F,detrend=TRUE,demean=TRUE)                                                                                                                                                        
  resA1$freq <- 1/resA1$freq                                                                                                                                                                                                                 
                                                                                                                                                                                                                                             
  restbl <- data.frame(Freq=round(resA1$freq[resA1$freq >= 120 & resA1$freq <= 280]),Cov=resA1$spec[resA1$freq >= 120 & resA1$freq <= 280])                                                                                                  
                                                                                                                                                                                                                                             
  valsA1 <- dataA1$V4/dataA1$V3                                                                                                                                                                                                              
  valsA1[is.na(valsA1)] <- 0                                                                                                                                                                                                                 
  tdataA1 <- as.ts(valsA1)                                                                                                                                                                                                                   
  tdataA1 <- filter(c(window(tdataA1,1,300),tdataA1),filter=1/seq(5,100,4),method="recursive")[-(1:300)]                                                                                                                                     
  tdataA1 <- tdataA1-mean(tdataA1,trim=0.1)                                                                                                                                                                                                  
                                                                                                                                                                                                                                             
  resA1 <- spec.pgram(tdataA1,pad=0.3,tap=0.3,span=2,plot=F,detrend=TRUE,demean=TRUE)                                                                                                                                                        
  resA1$freq <- 1/resA1$freq                                                                                                                                                                                                                 
  restbl$Starts <- resA1$spec[resA1$freq >= 120 & resA1$freq <= 280]                                                                                                                                                                         
                                                                                                                                                                                                                                             
  tdataA1 <- as.ts(dataA1$V5)                                                                                                                                                                                                                
  tdataA1 <- filter(c(window(tdataA1,1,300),tdataA1),filter=1/seq(5,100,4),method="recursive")[-(1:300)]                                                                                                                                     
  tdataA1 <- tdataA1-mean(tdataA1,trim=0.1)                                                                                                                                                                                                  
                                                                                                                                                                                                                                             
  resA1 <- spec.pgram(tdataA1,pad=0.3,tap=0.3,span=2,plot=F,detrend=TRUE,demean=TRUE)                                                                                                                                                        
  resA1$freq <- 1/resA1$freq                                                                                                                                                                                                                 
  restbl$WPS <- resA1$spec[resA1$freq >= 120 & resA1$freq <= 280]                                                                                                                                                                            
                                                                                                                                                                                                                                             
  gz1 <- gzfile(paste(opath,filename,sep="/"), "w")                                                                                                                                                                                          
  write.table(restbl, gz1, quote = F, sep = "\t", row.names = F)                                                                                                                                                                             
  close(gz1)                                                                                                                                                                                                                                 
}
